// Code generated by "stringer -type=IncomeType -output=incometype_gen.go"; DO NOT EDIT.

package benefits

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[REGU-0]
	_ = x[AFNI-1]
}

const _IncomeType_name = "REGUAFNI"

var _IncomeType_index = [...]uint8{0, 4, 8}

func (i IncomeType) String() string {
	if i >= IncomeType(len(_IncomeType_index)-1) {
		return "IncomeType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _IncomeType_name[_IncomeType_index[i]:_IncomeType_index[i+1]]
}
