// Code generated by "stringer -type=Region -output=regions_gen.go"; DO NOT EDIT.

package factory

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Canada-0]
	_ = x[NWT-1]
	_ = x[BC-2]
	_ = x[YT-3]
	_ = x[AB-4]
	_ = x[SK-5]
	_ = x[MB-6]
	_ = x[NU-7]
	_ = x[ON-8]
	_ = x[QC-9]
	_ = x[NL-10]
	_ = x[NB-11]
	_ = x[NS-12]
	_ = x[PE-13]
}

const _Region_name = "CanadaNWTBCYTABSKMBNUONQCNLNBNSPE"

var _Region_index = [...]uint8{0, 6, 9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33}

func (i Region) String() string {
	if i < 0 || i >= Region(len(_Region_index)-1) {
		return "Region(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Region_name[_Region_index[i]:_Region_index[i+1]]
}
